# ECH-Workers 默认配置（与命令行参数对应）
server_addr = ech.510524.xyz:443
local_listen = 127.0.0.1:1080
token = fage
preferred_ip = fage.cf.090227.xyz
doh_server = dns.alidns.com/dns-query
ech_domain = cloudflare-ech.com
routing = global
